"""
Base PINN Solver Class
"""
import torch
import torch.nn as nn
import numpy as np
from abc import ABC, abstractmethod
import time


class BasePINNSolver(ABC):
    """
    Abstract base class for PINN solvers
    
    This class provides common functionality for all PINN solvers,
    including training loop, loss computation, and prediction.
    """
    
    def __init__(self, model, config, device='cuda'):
        """
        Initialize the PINN solver
        
        Args:
            model: Neural network model
            config: Configuration dictionary
            device: Computing device ('cuda' or 'cpu')
        """
        self.model = model
        self.config = config
        self.device = torch.device(device if torch.cuda.is_available() else 'cpu')
        self.model.to(self.device)
        
        # Training parameters - ADD THESE
        self.epochs = config.get('epochs', 10000)
        self.learning_rate = config.get('learning_rate', 1e-3)
        
        # Training history
        self.loss_history = []
        self.loss_components_history = {
            'total': [],
            'ic': [],
            'bc': [],
            'pde': [],
            'data': []
        }
        
        # Optimizer and scheduler
        self.optimizer = None
        self.scheduler = None
        self._setup_optimizer()
        
        # Training data (to be generated by subclass)
        self.X_ic = None
        self.u_ic = None
        self.X_bc = None
        self.u_bc = None
        self.X_pde = None
        self.X_data = None
        self.u_data = None
    
    def _setup_optimizer(self):
        """Setup optimizer and learning rate scheduler"""
        lr = self.learning_rate  # Use self.learning_rate instead of config.get
        
        optimizer_type = self.config.get('optimizer', 'adam').lower()
        if optimizer_type == 'adam':
            self.optimizer = torch.optim.Adam(self.model.parameters(), lr=lr)
        elif optimizer_type == 'lbfgs':
            self.optimizer = torch.optim.LBFGS(
                self.model.parameters(), 
                lr=lr,
                max_iter=20,
                history_size=50
            )
        else:
            self.optimizer = torch.optim.Adam(self.model.parameters(), lr=lr)
        
        # Learning rate scheduler
        if self.config.get('use_scheduler', True):
            decay_steps = self.config.get('lr_decay_steps', 5000)
            decay_rate = self.config.get('lr_decay_rate', 0.9)
            self.scheduler = torch.optim.lr_scheduler.StepLR(
                self.optimizer, 
                step_size=decay_steps, 
                gamma=decay_rate
            )
    
    @abstractmethod
    def _generate_training_data(self):
        """Generate training data (IC, BC, PDE collocation points)"""
        pass
    
    @abstractmethod
    def pde_residual(self, X):
        """Compute PDE residual"""
        pass
    
    def loss_ic(self):
        """Compute initial condition loss"""
        if self.X_ic is None:
            return torch.tensor(0.0, device=self.device)
        
        u_pred = self.model(self.X_ic)
        return torch.mean((u_pred - self.u_ic) ** 2)
    
    def loss_bc(self):
        """Compute boundary condition loss"""
        if self.X_bc is None:
            return torch.tensor(0.0, device=self.device)
        
        u_pred = self.model(self.X_bc)
        return torch.mean((u_pred - self.u_bc) ** 2)
    
    def loss_pde(self):
        """Compute PDE residual loss"""
        if self.X_pde is None:
            return torch.tensor(0.0, device=self.device)
        
        residual = self.pde_residual(self.X_pde)
        return torch.mean(residual ** 2)
    
    def loss_data(self):
        """Compute data fitting loss (if available)"""
        if self.X_data is None:
            return torch.tensor(0.0, device=self.device)
        
        u_pred = self.model(self.X_data)
        return torch.mean((u_pred - self.u_data) ** 2)
    
    def compute_loss(self):
        """
        Compute total loss
        
        Returns:
            total_loss: Total weighted loss
            loss_dict: Dictionary of individual loss components
        """
        lambda_ic = self.config.get('lambda_ic', 1.0)
        lambda_bc = self.config.get('lambda_bc', 1.0)
        lambda_pde = self.config.get('lambda_pde', 1.0)
        lambda_data = self.config.get('lambda_data', 1.0)
        
        loss_ic_val = self.loss_ic()
        loss_bc_val = self.loss_bc()
        loss_pde_val = self.loss_pde()
        loss_data_val = self.loss_data()
        
        total_loss = (lambda_ic * loss_ic_val + 
                     lambda_bc * loss_bc_val + 
                     lambda_pde * loss_pde_val + 
                     lambda_data * loss_data_val)
        
        loss_dict = {
            'total': total_loss.item(),
            'ic': loss_ic_val.item(),
            'bc': loss_bc_val.item(),
            'pde': loss_pde_val.item(),
            'data': loss_data_val.item()
        }
        
        return total_loss, loss_dict
    
    def train_step(self):
        """Single training step"""
        self.model.train()
        
        def closure():
            self.optimizer.zero_grad()
            loss, _ = self.compute_loss()
            loss.backward()
            return loss
        
        if isinstance(self.optimizer, torch.optim.LBFGS):
            self.optimizer.step(closure)
            loss, loss_dict = self.compute_loss()
        else:
            self.optimizer.zero_grad()
            loss, loss_dict = self.compute_loss()
            loss.backward()
            self.optimizer.step()
        
        if self.scheduler is not None:
            self.scheduler.step()
        
        return loss, loss_dict
    
    def train(self, verbose=True, save_interval=1000):
        """Train the PINN model"""
        print("\n" + "="*80)
        print(f"Training {self.__class__.__name__}")
        print("="*80)
        print(f"Device: {self.device}")
        print(f"Epochs: {self.epochs}")
        print(f"Optimizer: {self.optimizer.__class__.__name__}")
        if self.scheduler is not None:
            print(f"LR Scheduler: {self.scheduler.__class__.__name__}")
        print("-"*80)
        
        start_time = time.time()
        
        for epoch in range(self.epochs):
            # Compute loss
            loss, loss_dict = self.train_step()
            
            # Store history
            self.loss_history.append(loss.item())
            for key, val in loss_dict.items():
                if key not in self.loss_components_history:
                    self.loss_components_history[key] = []
                self.loss_components_history[key].append(val)
            
            # Print progress
            if verbose and (epoch % 100 == 0 or epoch == self.epochs - 1):
                current_lr = self.optimizer.param_groups[0]['lr']
                elapsed = time.time() - start_time
                
                # Build loss string dynamically
                loss_str_parts = [f"Total = {loss_dict.get('total', loss.item()):.2e}"]
                
                # Define order for pretty printing
                display_keys = ['ic', 'bc', 'bc_inlet', 'bc_outlet', 'bc_wall', 
                               'bc_cylinder', 'pde', 'continuity', 'data']
                
                for key in display_keys:
                    if key in loss_dict and loss_dict[key] > 0:
                        label = key.replace('_', ' ').title()
                        loss_str_parts.append(f"{label} = {loss_dict[key]:.2e}")
                
                loss_str = ", ".join(loss_str_parts)
                
                print(f"Epoch {epoch:5d}/{self.epochs} | {loss_str} | LR = {current_lr:.2e} | Time = {elapsed:.1f}s")
        
        total_time = time.time() - start_time
        print("-"*80)
        print(f"✓ Training completed in {total_time:.1f}s")
        print("="*80 + "\n")
    
    def predict(self, X):
        """
        Make predictions
        
        Args:
            X: Input tensor or numpy array
        
        Returns:
            Predictions as numpy array
        """
        self.model.eval()
        
        if isinstance(X, np.ndarray):
            X = torch.tensor(X, dtype=torch.float32).to(self.device)
        elif not isinstance(X, torch.Tensor):
            raise TypeError("Input must be numpy array or torch tensor")
        
        with torch.no_grad():
            u_pred = self.model(X)
        
        return u_pred.cpu().numpy()
    
    def save_model(self, filepath):
        """Save model checkpoint"""
        torch.save({
            'model_state_dict': self.model.state_dict(),
            'optimizer_state_dict': self.optimizer.state_dict(),
            'loss_history': self.loss_history,
            'loss_components_history': self.loss_components_history,
            'config': self.config
        }, filepath)
        print(f"✓ Model saved to {filepath}")
    
    def load_model(self, filepath):
        """Load model checkpoint"""
        checkpoint = torch.load(filepath, map_location=self.device)
        self.model.load_state_dict(checkpoint['model_state_dict'])
        self.optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
        self.loss_history = checkpoint['loss_history']
        self.loss_components_history = checkpoint.get('loss_components_history', {})
        print(f"✓ Model loaded from {filepath}")
    
    def save_checkpoint(self, epoch):
        """Save training checkpoint (can be overridden by subclasses)"""
        pass